{% set name = "mmpose" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 463df5a591b6cb351140f52a1a6a5e74d9182392d09b8e6bab1f471daca5a21f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - numpy
    - pytorch >=1.8
  run:
    - chumpy
    - json_tricks
    - matplotlib
    - munkres
    - numpy
    - opencv-python
    - pillow
    - python >={{ python_min }}
    - requests
    - scipy
    - torchvision
    - xtcocotools >=1.12

test:
  imports:
    - mmpose
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-mmlab/mmpose
  summary: OpenMMLab Pose Estimation Toolbox and Benchmark
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
